name: life_in_months
description: Life visualized as 1080 months
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/int.png"
  min_sdk_android: 21 # optional

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
